const municipalities = [
	{ key: 1, value: "Buenavista", label: "Buenavista" },
	{ key: 2, value: "Cabadbaran", label: "Cabadbaran" },
	{ key: 3, value: "Carmen", label: "Carmen" },
	{ key: 4, value: "Jabonga", label: "Jabonga" },
	{ key: 5, value: "Kitcharao", label: "Kitcharao" },
	{ key: 6, value: "Las Nieves", label: "Las Nieves" },
	{ key: 7, value: "Magallanes", label: "Magallanes" },
	{ key: 8, value: "Nasipit", label: "Nasipit" },
	{ key: 9, value: "Remedios T. Romualdez", label: "Remedios T. Romualdez" },
	{ key: 10, value: "Santiago", label: "Santiago" },
	{ key: 11, value: "Tubay", label: "Tubay" },
	{ key: 12, value: "Bayugan", label: "Bayugan" },
	{ key: 13, value: "Bunawan", label: "Bunawan" },
	{ key: 14, value: "Esperanza", label: "Esperanza" },
	{ key: 15, value: "La Paz", label: "La Paz" },
	{ key: 16, value: "Loreto", label: "Loreto" },
	{ key: 17, value: "Prosperidad", label: "Prosperidad" },
	{ key: 18, value: "Rosario", label: "Rosario" },
	{ key: 19, value: "San Francisco", label: "San Francisco" },
	{ key: 20, value: "San Luis", label: "San Luis" },
	{ key: 21, value: "Santa Josefa", label: "Santa Josefa" },
	{ key: 22, value: "Talacogon", label: "Talacogon" },
	{ key: 23, value: "Trento", label: "Trento" },
	{ key: 24, value: "Veruela", label: "Veruela" },
	{ key: 25, value: "Alegria", label: "Alegria" },
	{ key: 26, value: "Bacuag", label: "Bacuag" },
	{ key: 27, value: "Burgos", label: "Burgos" },
	{ key: 28, value: "Claver", label: "Claver" },
	{ key: 29, value: "Dapa", label: "Dapa" },
	{ key: 30, value: "Del Carmen", label: "Del Carmen" },
	{ key: 31, value: "General Luna", label: "General Luna" },
	{ key: 32, value: "Gigaquit", label: "Gigaquit" },
	{ key: 33, value: "Mainit", label: "Mainit" },
	{ key: 34, value: "Malimono", label: "Malimono" },
	{ key: 35, value: "Pilar", label: "Pilar" },
	{ key: 36, value: "Placer", label: "Placer" },
	{ key: 37, value: "San Benito", label: "San Benito" },
	{ key: 38, value: "San Isidro", label: "San Isidro" },
	{ key: 39, value: "Santa Monica", label: "Santa Monica" },
	{ key: 40, value: "Sison", label: "Sison" },
	{ key: 41, value: "Socorro", label: "Socorro" },
	{ key: 42, value: "Tagana-an", label: "Tagana-an" },
	{ key: 43, value: "Tubod", label: "Tubod" },
	{ key: 44, value: "Barobo", label: "Barobo" },
	{ key: 45, value: "Bayabas", label: "Bayabas" },
	{ key: 46, value: "Bislig", label: "Bislig" },
	{ key: 47, value: "Carrascal", label: "Carrascal" },
	{ key: 48, value: "Cortes", label: "Cortes" },
	{ key: 49, value: "Hinatuan", label: "Hinatuan" },
	{ key: 50, value: "Lanuza", label: "Lanuza" },
	{ key: 51, value: "Lianga", label: "Lianga" },
	{ key: 52, value: "Lingig", label: "Lingig" },
	{ key: 53, value: "Madrid", label: "Madrid" },
	{ key: 54, value: "Marihatag", label: "Marihatag" },
	{ key: 55, value: "San Agustin", label: "San Agustin" },
	{ key: 56, value: "San Miguel", label: "San Miguel" },
	{ key: 57, value: "Tagbina", label: "Tagbina" },
	{ key: 58, value: "Tago", label: "Tago" },
	{ key: 59, value: "Tandag", label: "Tandag" },
	{ key: 60, value: "Butuan", Label: "Butuan" },
];

export default municipalities;
